### ISSUE TITLE
extensionapi:info throws error

### ISSUE THREAD

**Issue by thomashohn** [TYPO3-coreapi/ext-coreapi#108]
If ./cli_dispatch.phpsh extbase extensionapi:info is called with an extension that is not installed it throws the following error:
PHP Warning: Invalid argument supplied for foreach() in /Users/tho/flat-sysgit/ibog-extensions/coreapi/Classes/Command/ExtensionApiCommandController.php line 103
since the $data['em_conf']  is empty if a if (!empty($data['em_conf'] )) is placed around the foreach it will return that the extension is not installed instead of an run-time error

**Comment by etobi** [comment]
Hej,

thanks for your report and your suggestion. Could you prepare and send a PullRequest? I will review and merge it then.

**Comment by thomashohn** [comment]
Hi - if you could guide me to create the pull-request - I can do it :-)

**Comment by etobi** [comment]
Sure. You need to fork our repository into your github-account, checkout that repo, commit the bugfix, push it to github and then create a pull request.
Check https://help.github.com/articles/fork-a-repo/ and https://help.github.com/articles/using-pull-requests/ on how forking and PullRequests working on github.

Looking forward to your first PR :-)

regards
  tobias

**Comment by thomashohn** [comment]
Hi

Hope you have recieved a PR from me

Greetings

Thomas


2015-09-29 9:51 GMT+02:00 Tobias Liebig <notifications@github.com>:

> Sure. You need to fork our repository into your github-account, checkout
> that repo, commit the bugfix, push it to github and then create a pull
> request.
> Check https://help.github.com/articles/fork-a-repo/ and
> https://help.github.com/articles/using-pull-requests/ on how forking and
> PullRequests working on github.
>
> Looking forward to your first PR :-)
>
> regards
> tobias
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TYPO3-coreapi/ext-coreapi/issues/108#issuecomment-143976521>
> .
>



-- 
Venlig hilsen

Thomas Hohn
IT-udvikler
E-mail: tho@systime.dk
Tlf.: 30 36 08 16

-- 

<http://systime.dk/>
Adresse 
<https://www.google.dk/maps/place/Systime+A%2FS/@56.14616,10.201086,17z/data=!3m1!4b1!4m2!3m1!1s0x464c3f8bf58bade9:0xbbaee26f436fbfc3>
 | +45 7012 1100 | systime.dk

<http://systimes.idebat.dk/>
