### ISSUE TITLE
Version 1.3.0 not on packagist

### ISSUE THREAD

**Issue by jdreesen** [TYPO3-coreapi/ext-coreapi#118]
Somehow the latest tagged version 1.3.0 doesn't appear on packagist. It says the latest version is still v1.2.1: https://packagist.org/packages/etobi/coreapi

**Comment by Konafets** [comment]
I made a update on Packagist.

**Comment by jdreesen** [comment]
Great, thx :)

**Comment by etobi** [comment]
@Konafets what do i need to do to release it to packagist? I thought tagging in git and doing a release on github should be thing.

**Comment by oliverklee** [comment]
Log in to packagist, go to "my packages", click on the package name, an then click the green "Update" button.

**Comment by Konafets** [comment]
It looks like the webhook is not working. Don't know if the reason is because this repository belongs to @etobi while the packagist account belongs to me.

**Comment by oliverklee** [comment]
In the emogrifier project, we also have similar issues because there the repository owner is not the same as the packagist package owner.
